### ISSUE TITLE
Build failure with new luarocks commits

### ISSUE THREAD

**Issue by Earnestly** [simoncozens/sile#659]
Having been building sile for many months, recent changes have broken it:

```sh
    autoreconf -fi

    # XXX autotools automatically creates this for storing coredumps for its
    # tests which is then later removed.  As this codebase contains a core
    # directory of its own we need to make sure the configure script isn't
    # able to remove it.
    sed -i 's/rm -f core/rm -f/' configure

    ./configure --prefix=/usr --with-system-libtexpdf
    make
```

```
find: 'lua_modules': No such file or directory
find: 'lua_modules': No such file or directory
find: 'lua_modules': No such file or directory
bash: luarocks: command not found
bash: luarocks: command not found
Makefile:1028: target '.PRECIOUS' doesn't match the target pattern
Making all in src
make[1]: Entering directory '/home/earnest/build/staging/sile-git/src/sile/src'
  CC       justenoughharfbuzz_la-justenoughharfbuzz.lo
  CC       justenoughlibtexpdf_la-justenoughlibtexpdf.lo
  CC       justenoughlibtexpdf_la-imagebbox.lo
  CC       justenoughfontconfig_la-justenoughfontconfig.lo
  CC       fontmetrics_la-fontmetrics.lo
  CC       svg_la-svg.lo
justenoughharfbuzz.c: In function 'shape':
justenoughharfbuzz.c:150:33: warning: initialization discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  150 |     char * shaper_list_string = luaL_checkstring(L, 9);
      |                                 ^~~~~~~~~~~~~~~~
justenoughharfbuzz.c:202:91: warning: passing argument 5 of 'hb_shape_plan_create_cached' from incompatible pointer type [-Wincompatible-pointer-types]
  202 |     shape_plan = hb_shape_plan_create_cached(hbFace, &segment_props, features, nFeatures, shaper_list);
      |                                                                                           ^~~~~~~~~~~
      |                                                                                           |
      |                                                                                           char **
In file included from /usr/include/harfbuzz/hb.h:40,
                 from justenoughharfbuzz.c:4:
/usr/include/harfbuzz/hb-shape-plan.h:49:1: note: expected 'const char * const*' but argument is of type 'char **'
   49 | hb_shape_plan_create_cached (hb_face_t                     *face,
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  CC       justenoughicu_la-justenoughicu.lo
  CCLD     justenoughlibtexpdf.la
  CCLD     justenoughfontconfig.la
  CCLD     fontmetrics.la
  CCLD     justenoughharfbuzz.la
  CCLD     justenoughicu.la
  CCLD     svg.la
cp .libs/justenoughharfbuzz.so .libs/justenoughfontconfig.so  .libs/justenoughlibtexpdf.so .libs/fontmetrics.so .libs/svg.so .libs/justenoughicu.so ../core
make[1]: Leaving directory '/home/earnest/build/staging/sile-git/src/sile/src'
make[1]: Entering directory '/home/earnest/build/staging/sile-git/src/sile'
find: 'lua_modules': No such file or directory
find: 'lua_modules': No such file or directory
find: 'lua_modules': No such file or directory
bash: luarocks: command not found
bash: luarocks: command not found
Makefile:1028: target '.PRECIOUS' doesn't match the target pattern
luarocks --tree lua_modules  install --only-deps sile-dev-1.rockspec
bash: luarocks: command not found
make[1]: *** [Makefile;967: lua_modules] Error 127
make[1]: Leaving directory '/home/earnest/build/staging/sile-git/src/sile'
```

Breaking commit: https://github.com/simoncozens/sile/commit/b02c1ecce8f74beb8d8edd41cccc63a02a353296

On a side note, please don't use anything that requires an internet connection during a build.

**Comment by alerque** [comment]
At the moment an internet connection _is_ required, not as part of the actual build, but as part of a prep stage that gets dependencies. We use a lot of 3rd party Lua libraries. Previously we required a mix of these being installed on the system and some that we bundled in our source code. This was making packaging a fiasco and producing inconsistent results, not to mention being a maintenance headache because updating bundled code was so painful it wasn't happening.

I expect when we build source releases that we will bundle up the `lua_modules` directory with the tarball so that it produces reproducible results (and can be used offline). Until the next tagged release an internet connection will be required to fetch various lua rocks. If you want to build the documentation or run the test suite it will also download an assortment (of appropriately licensed) fonts for those.

The second issue I see in that error is that you don't seem to have luarocks installed on your system. That is required to build from a git checkout at this point. It will not be required of tagged released and building from a source tarball, but we don't have a tagged release with this new code layout yet.

Until the next tagged release, please install luarocks and, if you want to be able to build offline, run `make prep` after cloning to fetch the dependencies. You should be able to run `make` or pretty much any of the other targets offline after that.

**Comment by alerque** [comment]
Please do report back here if adding luarocks to your system does or doesn't get you past this issue, and if you have any ongoing problems building. I'll be working on build documentation and the release process based on this feedback.

**Comment by Earnestly** [comment]
Can luarocks be configured to not pull remote dependencies?  I really don't want to use language package managers in a build system.

**Comment by alerque** [comment]
I'm a little confused as to what you expect @Earnestly. Almost all languages these days use packages managers as part of their build system(s). Javascript has `npm install` that you run before `npm build`, Rust has `cargo install` that you run before `cargo build`, Python has `pip install -e` that you run before `./setup.py`, Ruby has `gem ` that you run before ` C++ has `(conan,vcpkg,nbuckaroo,hunter,cpm,pacm,spack,...)` that you run before I don't even know what these days, etc. Don't eve get me started on Go which has difficulty even using locally supplied dependencies. I could go on but the point is that using a tool to tap into the library ecosystem for a language is pretty much standard procedure.

Some of these have offline modes, ways to override remotes and look for local packages, etc. In our case we should be able to bundle the `lua_modules` directory in source tarballs and it won't even look at for them online when it is supplied locally.

What would you expect to have happen here?

Note: Since Lua does not have a way to disambiguate package versions installed globally and many distributions don't have many Lua packages anyway, we cannot rely on host systems having the dependencies we need (hence the fetching our own versions and bundling approach).

**Comment by Earnestly** [comment]
Please, please don't do this.  Please don't try to justify this with "well everyone else does it". The system worked, and yes you've listed problems with Go (Rust is just as guilty) as an example, and yes it causes countless hours of lost time debugging and wrangling these awful systems to work and integrate nicely with existing systems.

I would expect you to revert back to a working buildsystem that doesn't depend on a language package manager or at least makes it optional behind configure.

I can easily provide all the lua dependencies needed without issue, and it all still works if I comment out the added luarocks instructions from the `Makefile`.

PS: There is also an issue with incorrect use of make: `Makefile:1028: target '.PRECIOUS' doesn't match the target pattern`

**Comment by alerque** [comment]
Re `Makefile:1028` I fixed this an hour or so ago in  #590. There is a stray colon, sorry about that. In only turns into an error when running `clean-benchmarks`.

I'm happy to help provide a mechanism for systems which happen to have system packages for Lua that supply all the dependencies. This is previously how I packaged it for Arch Linux: by writing a bunch of Lua packages that as well. If you really want to build without local copies of the Lua dependencies we can have a target for that to run _at your own risk_.

However it is not possible for that to be the default because many/most systems do not have all the required Lua dependencies as system packages, and many that have some of them are incomparable versions. We already fought this for a long time and it is severely hindering SILE adoption because it has been very difficult to install and run on many platforms. This eases that greatly even compiling from git (`luarocks` is far more available than all the rocks we need) and it will make it even easier to build from source tarballs (as generated from `make dist`) which will not even require Luarocks or any network.

There is not a working build system to revert to, only a very broken one that we couldn't get to work on many platforms.

**Comment by Earnestly** [comment]
Yes, a flag that prevents the use of luarocks, and lets me use the system libraries would be ideal - I'm sure virtually every Linux distribution would want this, at least those which don't support bundling.

I'm still bitterly disappointed with this rationale, my heart sank at the outright ad-populum justification.  Obviously my personal experience has shown these changes have caused more hinderence than help.  But never mind, for the short term I can apply a small local patch that removes the use of `luarocks` until I eventually retire the package completely.

**Comment by alerque** [comment]
What system are you on and what do you mean by "doesn't support bundling"? I'm not trying to be difficult here I genuinely don't know what you mean by that in the context that I have described here. I don't know of _any_ distros that will not support what we are doing including 3rd party Lua libraries in a project local location in our source distribution to be installed local to SILE itself.

In fact this was my solution to make it possible to package SILE on all the distros that did not support anything _else_. Homebrew doesn't even have a proper mechanism for handling Lua dependencies, much less have packages for them all. Ubuntu has about half of what we need and impossibly old versions of what it does have. Fixing this deficit is impossible with their LTS release paradigm. 

We simply have to bundle a lot of our own code in releases or we won't get packaged on most systems. We're not spewing it across the system either, we're keeping what we need in the way of 3rd party code close at hand next to own own 1st party code, and setting our internal Lua include paths to reflect this.

What would you propose?

**Comment by alerque** [comment]
Reviewing our conversation I think there is something missing. I believe these points are a misunderstanding of what we're doing:

> On a side note, please don't use anything that requires an internet connection during a build.

We won't be requiring an internet connection during a build. All the source will be included in the source tarball (which can be checksumed/signed).

> a flag that prevents the use of luarocks

Luarocks is only required now to setup a development environment from a git clone. **It is not and will not be required to build, run, or install from source**, and will not be a requirement for distro packages (at least not tagged releases, it will be optional for *-git based devel builds, we can add optional flag(s) to `--use-system-lua-*` to the autoconf setup).

**Comment by alerque** [comment]
I'm re-opening issue report because this is the best place I see to track that we eventually make sure `./configure` has the option to use system installed Lua Rocks (not `luarocks` which is not required at all, just the code packages themselves) and/or that `pkg-config` is used to detect any available Lua dependencies in lieu of bundling those 3rd party libraries.

**Comment by alerque** [comment]
See also #643 and #638.

**Comment by Earnestly** [comment]
That is fine.  After all you're doing the work for this and I don't mean to demand anything from you.  If sile wants to go in one direction that I find distasteful then that's my problem to deal with.

For what its worth, I want to build software like this from git (or latest VCS) for several reasons (including timely, and relevant bug reports).  However, I dislike the notion that there should be separate "developmental" and "distributable" sources.  If a project cannot be built reliably, and reasonably (i.e. using the same build instructions) from latest code source then it's a bug I have to try and solve or workaround.  Alternatively if the software is not worth the effort then to abandon it.

Fortunately the vast majority of software I have packaged (~400 now, apparently) from latest VCS are quite sensible.

**Comment by Earnestly** [comment]
You can reopen it by all means, after all you're doing the work and I don't mean to demand anything.

There's too much to address and so many fundamental disagreements from how and what responsibilities a makefile should have, the use of autotools, how dependencies should be managed, the concept of "development source" and "distributed source" code, how to interact with downstream maintainers, what changelogs (i.e. NEWS files) should contain, the practice of making downstream modifications to upstream code, bundling, etc., etc.  I'm sorry this has been a bit of a low effort post, I'm too tried.

I hope you also noticed the issue of having to prevent the generated `./configure` script from removing the `core` directory.  If anything, that's something worth looking into.

**Comment by eli-schwartz** [comment]
> What system are you on and what do you mean by "doesn't support bundling"? I'm not trying to be difficult here I genuinely don't know what you mean by that in the context that I have described here. I don't know of any distros that will not support what we are doing including 3rd party Lua libraries in a project local location in our source distribution to be installed local to SILE itself.

Speaking as a developer for one of those distributions I can most assuredly confirm we don't support bundling. Actually I'm unsure of any distribution which supports it. It's usually a high-ranked policy item that such things are forbidden.

If you're being disingenuous and translating "doesn't support it" as "if we install unindentified files into the DESTDIR or equivalent packaging directory, no one will notice", I'd like to point out that there are worlds of difference between "technologically possible by cheating" and "distributions support and permit such packages to be created, uploaded, and distributed via distro channels".

Maybe it's time to finally read the policy documentation of Arch Linux, Debian, Fedora, or literally anything else?

...

I get that this is WIP stuff in git, and I am sympathetic to your need to get things working in a development environment and then work on integrating with distributor policies. I just don't understand how it is helpful to include offhand remarks about how you "don't know of any distros that will not support" sile-local bundled dependencies.

**Comment by alerque** [comment]
@Earnestly Thanks for the feedback, and I'm sorry this is a tiring process. No urgency, but I do still have some questions for you:

1. What distro are you using and packaging for? I would like to take a look at how it does things to get a better idea how to ease the process.

2. Change logs is something I implemented a major revision for so the next release will look a lot different. If you have input on where you would expect to find what news, it would be great to hear it. The current plan is to have CHANGELOG.md be updated with an automated process that [summaries the git change history](https://github.com/simoncozens/sile/issues/588#issuecomment-516728974) between releases. NEWS.md will have a smaller more hand curated summary of project changes. The Github release page and website announcement blog post will each have something like what goes in NEWS.md, and like to the relevant change log. Does that sound right to you?

3. Given ⓐ source tarballs will have all necessary code bundles, and can optionally use the bundled  versions or system versions at build time and ⓑ git checkouts can be compiled with no network access if the system provides all the Lua deps, or with network access to fetch 3rd party deps locally if not, are there any other changes you would suggest we make?

    I don't think I would call this layout a "development source" so much as a "development environment". Our source is our source, but the source distribution tarballs will also have extras (libtexpdf, various lua rocks) that can either be installed or not as distro packagers choose.

4. I did notice the issue with autoconf and core. In fact I experimented with renaming the directory later just because autoconf is so opinionated, but I couldn't find a better name so I ended up [further hacking it to allow it to be called core](https://github.com/simoncozens/sile/milestones?direction=asc&sort=title&state=open). If you have a suggestion here again lets hear it.

**Comment by alerque** [comment]
> Speaking as a developer for one of those distributions I can most assuredly confirm we don't support bundling. Actually I'm unsure of any distribution which supports it. It's usually a high-ranked policy item that such things are forbidden.

Hey @eli-schwartz thanks for chiming in. Can I ask what specifically you mean by "bundling" here? I have a feeling that we may mean entirely different things (maybe even 3 different things between you, me, and @Earnestly) and I'd like to get that straightened out. I think you guys might be thinking of something much more intrusive / uncouth than what I meant. Perhaps I'm using the wrong word entirely, in which case feel free to suggest a better one. What is your definition of "bundling"?

I'm pretty sure we don't want to buck any distro policies here. I just don't think we're all even talking about the same thing.

**Comment by eli-schwartz** [comment]
If the source tarball contains a code copy of another project, **even if it isn't used**, then some distros might insist on removing the code copy before building the project. I know of Debian packages that do this as part of their repackaging into *.orig.tar.xz source tarballs.

Arch Linux does not care if you have code copies in your source tarball, as long as there is an option to not use them (but instead rely on the system copy). As a general rule, distributions want at least this much, and mandate by packaging policy that the system copy be used (without attempting to download and compile them in the process!!!).

Given this issue was opened essentially because the current git master did not support that, and @Earnestly linked me to this issue, I thought I'd pop by and give my take on it. I'm pretty sure he has the same concern as me, because we are both Arch Linux users who care about proper packaging for Arch Linux.

It is my understanding that you intend to make this work cleanly from a distribution perspective. Which is appreciated. But I think it would probably be helpful to avoid statements that **imply** you are trivializing such concerns because you exclusively care about end users:
- installing via homebrew (which doesn't care how you package it)
- git cloning your repository and having it magically work without thinking, because distros don't happen to have packages **yet** for your dependencies

BTW "the dependencies aren't packaged" is not a problem exclusive to lua. To use your previous python example, lots of people `pip install foo` and download 666 dependecies in the process because the distro doesn't have it available yet. That still doesn't mean it is remotely acceptable for people to attempt to contribute a distro package that runs pip and installs 666 dependencies into a virtualenv and then packages the virtualenv.

**Comment by alerque** [comment]
@Earnestly and @eli-schwartz. Thanks for the detailed feedback to date.

If I'm not mistaken [this set of changes](https://github.com/simoncozens/sile/pull/590/files/3c2f8a3792c7a91beb3acb32207150ca59c5a321..6c1ae1aaed15ef1e33c083b87ed03e24db2f9ae7) should address your concerns by introducing a configuration flag and allowing `./configure --with-system-luarocks` which completely skips any attempt to fetch and bundle standard Lua Rocks alongside the SILE code.

I was unsure how to handle the one Lua Rock (`compat53`) that is only required for Lua <= 5.2 in the autoconf setup; `luarocks` handles this by itself so the rockspec doesn't need any help. This isn't a problem on Arch Linux where the default is Lua 5.3 anyway, but it might be a problem on other distributions and if you know the correct way to fix this I'd love to hear it. For now I've just avoided mentioning it to autoconf at all.

**Comment by alerque** [comment]
@Earnestly Let me know if there are any unresolved issues building and packaging v0.10.0 (esp. in your case with the new option `./configure --with-system-luarocks`) and if there is anything that needs to be pushed through I'll be happy to make a point release so it is addressed sooner rather than later.

**Comment by Earnestly** [comment]
The changes for system luarocks have been perfectly fine and I am able to supply all the lua dependencies myself, thank you for this.

The only issue remaining would be from autotools generating a configure script that attempts to remove the `core` directory.  See below my notes on the cause:

```sh
    autoreconf -fi


    # XXX aclocal pulls in macros from prog-cc-c-o.m4 (_AM_PROG_CC_C_O) into
    # aclocal.m4 that includes the command:

    #   rm -f core conftest*

    # As a result ./configure will attempt to remove a file called 'core' and
    # because this codebase has a directory named 'core' we will see spurious
    # warnings from rm:

    #   checking lua.h usability... rm: cannot remove 'core': Is a directory

    # To workaround this I am going to strip out the reference from the
    # generated configure script.
    sed -i 's/rm -f core/rm -f/' configure

    ./configure --prefix=/usr --with-system-libtexpdf --with-system-luarocks
    make
```

Without this the following errors are reported (although appear harmless):

```
[...]
checking lua.h usability... rm: cannot remove 'core': Is a directory
yes
checking lua.h presence... yes
checking for lua.h... yes
checking lualib.h usability... rm: cannot remove 'core': Is a directory
yes
checking lualib.h presence... yes
checking for lualib.h... yes
checking lauxlib.h usability... rm: cannot remove 'core': Is a directory
yes
checking lauxlib.h presence... yes
checking for lauxlib.h... yes
checking luaconf.h usability... rm: cannot remove 'core': Is a directory
yes
checking luaconf.h presence... yes
checking for luaconf.h... yes
checking for Lua header version... rm: cannot remove 'core': Is a directory
5.3
checking if Lua header version matches 5.3... yes
checking if LUA_VERSION is defined... yes
checking for library containing exp... rm: cannot remove 'core': Is a directory
rm: cannot remove 'core': Is a directory
-lm
checking for library containing dlopen... rm: cannot remove 'core': Is a directory
rm: cannot remove 'core': Is a directory
-ldl
checking for library containing lua_load... rm: cannot remove 'core': Is a directory
rm: cannot remove 'core': Is a directory
[...]
```

*PS: I see there is still a `./bootstrap.sh` script. Much like the old `autogen.sh`, these are discouraged over usage of `autoreconf`[*](https://lists.gnu.org/archive/html/autoconf/2007-08/msg00062.html) unless absolutely necessary.*

**Comment by alerque** [comment]
@Earnestly I've tried to get rid of the bloody bogus `rm -f core` for years and probably tried 20 different arrangements. I'd be happy to squash that once and for all but I still don't know how. There is currently a kludge in configure.ac to remove it, but it only works on 2nd and later configs, not out of the gate. If you know the correct place to fix this I'm all ears! Currently you're fixing it the same way I am, an install/packaging time (or ignoring it).

I'm also happy to ditch the bootstrap script if there was a fool proof way to have users issue a couple of commands and be up and running on BSD/Linux/etc. The git submodule we could tell people to fire up themselves, but the platform differences to Darwin are more pernicious. If there is a proper way to setup autoreconf so that it works out of the box for everybody the only thing holding us back is our own ignorance.
